version: '3.8'

services:
  php:
    build:
        dockerfile: ./docker/php/Dockerfile
    container_name: phpunit-container
    volumes:
      - .:/app
    working_dir: /app
    command: "tail -f /dev/null"
    depends_on:
      - mysql
      - redis
    networks:
      - phpnet
    environment:
        - REDIS_SCHEME=${REDIS_SCHEME}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - DB_HOST=${DB_HOST}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=$DB_PASSWORD

  mysql:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_HOST: '%'
      MARIADB_USER: test
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - phpnet

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - phpnet

networks:
  phpnet:
    driver: bridge
